// Generated by scripts/generate-app-theme.mjs from app/globals.css.
// Do not edit. Change the token there and re-run the script.
//
// React Native cannot read CSS custom properties, so the palette is mirrored
// here. globals.css is the source of truth; this file is an output, and CI
// fails if it is stale.

export const palettes = {
  light: {
    canvas             : "#f5f1e9",
    surface            : "#ffffff",
    surfaceSunken      : "#ece4d7",
    border             : "#e8e1d5",
    borderStrong       : "#d6cbb8",
    ink                : "#1a1a1a",
    inkMuted           : "#5c5449",
    inkSubtle          : "#6f665a",
    brand              : "#ce3f23",
    brandHover         : "#f44a35",
    brandDeep          : "#a8321c",
    brandSoft          : "#fbe9e5",
    brandTint          : "#fdf5f2",
    brandInk           : "#ffffff",
    accent             : "#ffc446",
    accentHover        : "#f0b02e",
    accentSoft         : "#fff3d4",
    accentInk          : "#805718",
    secondary          : "#a8321c",
    secondaryHover     : "#ce3f23",
    secondarySoft      : "#fbe9e5",
    secondaryInk       : "#ffffff",
    statusNew          : "#ce3f23",
    statusNewSoft      : "#fbe9e5",
    statusPreparing    : "#8a5a00",
    statusPreparingSoft: "#fff3d4",
    statusReady        : "#a8321c",
    statusReadySoft    : "#fbe9e5",
    statusCompleted    : "#6b6157",
    statusCompletedSoft: "#f0ebe1",
    statusCanceled     : "#3a352f",
    statusCanceledSoft : "#e9e4da",
    success            : "#a8321c",
    warning            : "#8a5a00",
    danger             : "#b3331b",
    dangerSoft         : "#fbe9e5",
  },
  dark: {
    canvas             : "#15110d",
    surface            : "#221c16",
    surfaceSunken      : "#2c241c",
    border             : "#382e24",
    borderStrong       : "#4d4032",
    ink                : "#f8f2e7",
    inkMuted           : "#c6b9a6",
    inkSubtle          : "#a99c8a",
    brand              : "#e2482a",
    brandHover         : "#f9553c",
    brandDeep          : "#ff8f78",
    brandSoft          : "#3a1a12",
    brandTint          : "#241611",
    brandInk           : "#ffffff",
    accent             : "#ffc446",
    accentHover        : "#ffd36f",
    accentSoft         : "#3a2c10",
    accentInk          : "#ffd36f",
    secondary          : "#ff8f78",
    secondaryHover     : "#f9553c",
    secondarySoft      : "#3a1a12",
    secondaryInk       : "#15110d",
    statusNew          : "#e2482a",
    statusNewSoft      : "#3a1a12",
    statusPreparing    : "#ffc446",
    statusPreparingSoft: "#3a2c10",
    statusReady        : "#ff8f78",
    statusReadySoft    : "#3a1a12",
    statusCompleted    : "#a99c8a",
    statusCompletedSoft: "#2c241c",
    statusCanceled     : "#a99c8a",
    statusCanceledSoft : "#2c241c",
    success            : "#ff8f78",
    warning            : "#ffc446",
    danger             : "#ff7a5e",
    dangerSoft         : "#3a1a12",
  },
} as const;

export type Scheme = keyof typeof palettes;
export type Palette = (typeof palettes)[Scheme];
export type ColorToken = keyof Palette;

/** Light, for anything that has to name a colour outside a React tree. */
export const tokens = palettes.light;
