// Generated by scripts/generate-app-theme.mjs from app/globals.css.
// Do not edit. Change the token in @theme and re-run the script.
//
// React Native cannot read CSS custom properties, so the palette is mirrored
// here. globals.css is the source of truth; this file is an output, and CI
// fails if it is stale.

export const tokens = {
  canvas             : "#f5f1e9",
  surface            : "#ffffff",
  surfaceSunken      : "#ece4d7",
  border             : "#e8e1d5",
  borderStrong       : "#d6cbb8",
  ink                : "#1a1a1a",
  inkMuted           : "#5c5449",
  inkSubtle          : "#6f665a",
  brand              : "#ce3f23",
  brandHover         : "#f44a35",
  brandDeep          : "#a8321c",
  brandSoft          : "#fbe9e5",
  brandTint          : "#fdf5f2",
  brandInk           : "#ffffff",
  accent             : "#ffc446",
  accentHover        : "#f0b02e",
  accentSoft         : "#fff3d4",
  accentInk          : "#805718",
  secondary          : "#a8321c",
  secondaryHover     : "#ce3f23",
  secondarySoft      : "#fbe9e5",
  secondaryInk       : "#ffffff",
  statusNew          : "#ce3f23",
  statusNewSoft      : "#fbe9e5",
  statusPreparing    : "#8a5a00",
  statusPreparingSoft: "#fff3d4",
  statusReady        : "#a8321c",
  statusReadySoft    : "#fbe9e5",
  statusCompleted    : "#6b6157",
  statusCompletedSoft: "#f0ebe1",
  statusCanceled     : "#3a352f",
  statusCanceledSoft : "#e9e4da",
  success            : "#a8321c",
  warning            : "#8a5a00",
  danger             : "#b3331b",
  dangerSoft         : "#fbe9e5",
} as const;

export type ColorToken = keyof typeof tokens;
